/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment': typeof PaymentRoute
  '/shop': typeof ShopRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment': typeof PaymentRoute
  '/shop': typeof ShopRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/payment': typeof PaymentRoute
  '/shop': typeof ShopRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/order-confirmed'
    | '/payment'
    | '/shop'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/order-confirmed'
    | '/payment'
    | '/shop'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/custom-order'
    | '/order-confirmed'
    | '/payment'
    | '/shop'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomOrderRoute: typeof CustomOrderRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PaymentRoute: typeof PaymentRoute
  ShopRoute: typeof ShopRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomOrderRoute: CustomOrderRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PaymentRoute: PaymentRoute,
  ShopRoute: ShopRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
